---
driver:
  name: terraform

platforms:
  - name: aws

suites:
  - name: minimal
    provisioner:
      name: terraform
      variable_files:
        - "test/fixtures/minimal/minimal.tfvars"
      apply_timeout: 600
      color: false
      directory: >-
        test/fixtures/minimal
      variables:
        user: <%= ENV['USER'] %>
    verifier:
      name: terraform
      format: doc
      groups:
        - name: terraform
          controls:
            - terraform_state
            - s3
